### ISSUE TITLE
Missing config.js file

### ISSUE THREAD

**Issue by samartha230194** [StephenGrider/AdvancedReduxCode#8]
the server side program requires config.js

**Comment by koesper** [comment]
I ran into the same problem, but it makes sense that it isnt included.
It is created during this screencast: https://www.udemy.com/react-redux-tutorial/learn/v4/t/lecture/4755174?start=80

but the contents are basically:

`module.exports = {
    secret: '' //your darkest secret here
}`

**Comment by samartha230194** [comment]
got that.. Thank you
